### ISSUE TITLE
Smoke trail works incorrectly at high enough relative velocities

### ISSUE THREAD

**Issue by BurgerKerman** [M1rageDev/Firefly#18]
The smoke trail that appears behind vehicles starts working incorrectly when two loaded vehicles have a high enough relative velocity (observed in Kerbin atmosphere at about 150 m/s relative). At these velocities the particle trail of the unselected vehicle becomes misaligned or starts pointing in the different direction than the vehicle's actual direction of travel.

Since I'm bad at explaining stuff I attached some pictures (all images are stock from MM and Firefly, all captured in version 1.12.5 of KSP with MH and BG installed; Firefly version 1.0.0, BUT still happens in 1.0.1).

1) The issue (green is the selected (active) vehicle, yellow are examples)
![Image](https://github.com/user-attachments/assets/8e0e7163-44f2-4093-bf44-e63abd03eb17)
2) Up close of one of the examples, note the discrepancy in directions
![Image](https://github.com/user-attachments/assets/4396f601-f54c-4de6-91de-6c984d523716)
3) Even closer
![Image](https://github.com/user-attachments/assets/214b5a4b-0bd1-4aeb-a885-e570fa57517b)
4) After switching to that vehicle, the trail is fixed
![Image](https://github.com/user-attachments/assets/24da197c-e2e4-4181-a8f6-4724af72089f)

Steps to reproduce (using the stock "Station One" scenario, though it will probably work under similar conditions):
1) Boot up the scenario
2) Deorbit the station (periapsis should be barely under the surface)
3) When the station enters the atmosphere, undock all modules
4) Remain focused on one of the modules (Aeris 4A is the better option as it will be leading all other fragments cause of better aerodynamics)
5) Wait until one of the modules will have a high enough relative velocity
6) ...
7) Loss? (as in antonym of profit)

Log file of reproduction in Firefly ver. 1.0.1 is attached.
[KSP.log](https://github.com/user-attachments/files/18873918/KSP.log)
(zips and 7z-s are my mods that I disabled for testing)

sorry if my english is bad

**Comment by M1rageDev** [comment]
Thanks for reporting!
Looks very weird, I'll look into it.

**Comment by M1rageDev** [comment]
Seems to be fixed in the latest commit, keeping the issue open until you can confirm that it works once I release the update.

**Comment by BurgerKerman** [comment]
Tried out 1.0.2: unfortunately is only partially fixed - now this behavior can be seen at 400-500 m/s relative speed (also seems to look a bit different?).

![Image](https://github.com/user-attachments/assets/6968ab46-6d4f-4e9a-9bfb-565fd84b73d8)

**Comment by M1rageDev** [comment]
Hm, does it also happen with the Reentry Particle Effect mod? I'll look into how it manages it's effects if it works properly

**Comment by M1rageDev** [comment]
Alright, I believe I've fixed it. I'll push a fix and release it in the next update.

**Comment by BurgerKerman** [comment]
Tried out 1.0.3: new particles look real nice! Unfortunately, the bug persists. The behavior is similar to 1.0.2.

![Image](https://github.com/user-attachments/assets/a259aa79-8de3-4407-9913-1e744c950cad)

**Comment by Nyonyix** [comment]
I can confirm this as well, I originally thought this was KSP physics being KSP physics and parts flying off in different directions. But after seeing this, This makes a lot more sense.

**Comment by M1rageDev** [comment]
I think I've manged to fix it - next update should get the changes. It still weirds out if the relative velocity is more than 400m/s, but it isn't as noticeable now.
